[env:waveshare_esp32_s3_lcd_128]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  moononournation/GFX Library for Arduino@1.4.9
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DDEVICE_VERSION=\"dev-2026.06.13.15\"
  -DOTA_MANIFEST_URL=\"https://raw.githubusercontent.com/mmarzook3/MotemaSens/device-release/mic_waveform_test/manifest.json\"
